### ISSUE TITLE
Runtime Permissions

### ISSUE THREAD

**Issue by Methe** [heitorcolangelo/kappuccino#92]
Not working! =(

`
doWait()
runtimePermission(Manifest.permission.ACCESS_COARSE_LOCATION) { deny() }
runtimePermission(Manifest.permission.ACCESS_FINE_LOCATION) { deny() }
doWait()
`

logcat:

`
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/test/uiautomator/UiDevice;
at br.com.concretesolutions.kappuccino.utils.PermissionUtils.handlePermission(PermissionUtils.kt:41)
at br.com.concretesolutions.kappuccino.utils.PermissionUtils.deny(PermissionUtils.kt:29)
at br.com.concretesolutions.kappuccino.utils.PermissionUtilsKt.runtimePermission(PermissionUtils.kt:15)
`

**Comment by Methe** [comment]
Found it!! I missed the UiAutomator dependendy!

Maybe the readme should be updated or the dependencies in the build.gradle should be 'api' instead of 'implementation'

**Comment by heitorcolangelo** [comment]
Fixed!
Thank you Methe
